# Generated by Django 3.1.5 on 2022-01-27 15:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20220126_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follow_list',
            field=models.ManyToManyField(blank=True, related_name='follows', to=settings.AUTH_USER_MODEL),
        ),
    ]
