# Generated by Django 3.1.4 on 2021-01-08 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210108_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='listing1',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='listing2',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='listing3',
            new_name='listing',
        ),
    ]
